### ISSUE TITLE
A MongoDBMembershipProvider's default options create an invalid MembershipProvider

### ISSUE THREAD

**Issue by ALyman** [freshlogic/MongoDB.Web#1]
The chosen combination of default configuration options { enablePasswordRetrieval = true, passwordFormat = hashed } means that not specifying either of these options creates a MembershipProvider that throws at initialization time.

```
    [TestMethod]
    public void CreatingWithNoOptions()
    {
        var membershipProvider = new MongoDBMembershipProvider();
        membershipProvider.Initialize("Fake", new NameValueCollection()); // throws
    }
```

**Comment by freshlogic** [comment]
Good catch. I think I'll set enablePasswordRetrieval = false by default.
