### ISSUE TITLE
Could not load type 'MongoDB.Web.Providers.MongoDBRoleProvider'

### ISSUE THREAD

**Issue by rolfwessels** [freshlogic/MongoDB.Web#21]
We have a website that works in IIS. We would like to host the website using owinhost or self hosting. 

When I run owin host it detects the requirement for the MongoDBRoleProvider but is unable to instantiate the type. 

Not sure where the issue comes from. Have you ever seen this issue 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'MongoDB.Web.Providers.MongoDBRoleProvider' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Any idea how to fix this issue?

**Comment by mizrael** [comment]
what .NET framework are you targeting ?

**Comment by rolfwessels** [comment]
4.51.

I think we have actually solved the issue. I will post it now

**Comment by rolfwessels** [comment]
The issue was that we did not specify the fully qualified name. Updating the config file to use  type="MongoDB.Web.Providers.MongoDBRoleProvider, MongoDB.Web". Solved the issue
