### ISSUE TITLE
Using MongoDB.Web with AppHarbor

### ISSUE THREAD

**Issue by osuritz** [freshlogic/MongoDB.Web#3]
AppHarbor will inject an appSettings entry named "MONGOHQ_URL" that points to the URL of the MongoDB instance. How can we make MongoDB.Web pickup that setting rather than inline connection string?

Should I add an extra appSettingsConnectionStringKey and submit a Pull Request?

**Comment by freshlogic** [comment]
I haven't played around with AppHarbor, but it sounds cool. If you'd like to give it a shot I'd be happy to take a look. Do you have any other connection string examples with AppHarbor?

**Comment by osuritz** [comment]
It's pretty much dynamic but here's a sample: mongodb://appharbor:[someGuid]@staff.mongohq.com:10041/[someOtherGuid]

**Comment by osuritz** [comment]
Here's the AppHarbor doc for using MongoDB on their platform: http://support.appharbor.com/kb/add-ons/using-mongohq

The tricky part is that their URL already specifies the database (see [someOtherGuid] in example above). I've almost got the Provider Initialize method code updated, I just need to figure out how to tell if the connection string includes a database ID in it or not.

**Comment by osuritz** [comment]
Submitted a pull request for this.
