### ISSUE TITLE
Membership - email uniqueness? Username Case-sensitvity?

### ISSUE THREAD

**Issue by Madd0g** [freshlogic/MongoDB.Web#8]
Hi,

Would it be possible to add case-insensitivity in usernames?
Also - I seem to be able to register with the same email twice. Is there a setting to control this?

Thank you

**Comment by DonMcNamara** [comment]
Hi,

It looks like the code supports email uniqueness. Try:
 requiresUniqueEmail="true"

This is the code in the membership provider:

```
        if (this.RequiresUniqueEmail && !String.IsNullOrWhiteSpace(this.GetUserNameByEmail(email)))
        {
            status = MembershipCreateStatus.DuplicateEmail;
            return null;
        }
```

**Comment by Madd0g** [comment]
Thank you, it does work, but also case-sensitive :-(
